### ISSUE TITLE
[RFC][OpenCL] Reduce kernel compilation time

### ISSUE THREAD

**Issue by kdobros** [plaidml/plaidml#1438]
For ResNet-50 kernel compilation takes ~96% of total execution time.
Some method to reduce this time is needed.

**Comment by kdobros** [comment]
Some propositions from me:
- Compile kernels during network compilation.
- Implement kernel cache, so only first iteration suffers.

IMHO Precompiling kernels makes most sense, but I'm not sure how much it's aligned with overall design.

@jbruestle @flaub @earhart @abialas1 @adstraw What do you think?

**Comment by jbruestle** [comment]
@earhart @flaub, correct any details I get wrong here:

We intend to do an early pass to split the 'main' entry point into three functions roughly along the lines of.

init(device) -> context
main(context, user_buffers) ->void
fini(context) -> void

Initially, context will contain only the device and the init, fini will be tiny, and most of the work will be done in main, and then various passes can move 'cachable' work (such as allocations, kernel compilation, and even copying of 'constant' buffers to the device) into init / fini 

Then, at the API level, when you construct an 'Executable' from a program, in addition to any low level passes to be finished, the 'init' function will be called (we may also add an explicit 'init' rather than doing at at construction time).  Thereafter, each 'run' will only call main, passing the context generated from init over and over again.  Finally, on destruction 'fini' will be called to release any resources.

**Comment by flaub** [comment]
Yes, additionally I'd say we'd like to do this splitting while the code is in `comp` dialect, so that we can apply it to many different backends. Ideally the `comp.create_execenv` would happen in `init` and the `comp.destroy_execenv` would happen in `fini`.

**Comment by earhart** [comment]
FWIW, #1434 implements the JitExecutable side of this pattern.  I'm working on a proposal for the comp dialect changes.

**Comment by earhart** [comment]
I wrote an RFC: https://github.com/plaidml/plaidml/wiki/RFC:-Network-Pre-Initialization
@jbruestle, @kdobros, @flaub -- PTAL?
(I'm thinking we can discuss it here, and edit the page as we go.)

**Comment by flaub** [comment]
Hey Rob, I have a bunch of comments to make, can we just post the RFC to a new issue?

There are a bunch of places where we say "we considered", but I think you meant "I (Rob) considered". Hopefully these are still open for discussion, because I've reached different conclusions on some of them, and would like to add more context to others which will hopefully mean we can reach a consensus.

**Comment by flaub** [comment]
Some comments:
* I'd like to rename `plaidml_execute` to `plaidml_main`
* I propose that instead of using `kidx` and `midx`, that we create new data types that represent kernels and memory chunks and then pass those into the `plaidml_main()` function. There's a bunch of values that don't go anywhere currently, there's a bunch of `comp.alloc` in `init` that I think we should pass those values to `main`. Same goes for kernels, the result of a `create_kernel` should get passed to `main`. Then `schedule` would use that value (and we could drop the `kidx`).
* I'm not sure we need a `get_alloc` if we just passed the memory chunk to `main`, we could just use the value directly.

**Comment by flaub** [comment]
nit: can you reformat the `.mlir` code so that it fits within 80 columns?

**Comment by flaub** [comment]
> We considered adding constant folding, but decided to defer it for now (do note how this could be used to optimize the code above a bit).

I'm actively working on this, so this is inaccurate. A PR will soon be submitted that does constant buffer folding.

**Comment by flaub** [comment]
> Note that we do not need or want to reify a !comp.kernel type for this, since we're going to use the exeecution environment as an opaque container. Instead, these operations should take an execution environment and a kernel index.

Why? Remember that MLIR uses values for basic things like canonicalizations and CSE. By using values we get these transformations for free.

**Comment by flaub** [comment]
> De-duplicate identical kernels.

We get this for free if we use values for kernels and we mark `create_kernel` as `NoSideEffect`. Then we have to ensure that all the attributes specified to the op guarantee its uniqueness.

**Comment by kdobros** [comment]
Thanks Rob for the RFC, great to see there is already some work on this!
In general I agree with everything Frank said above, some minor comments:

- I think `comp.create_kernel` should operate on device level since that's conceptually closer and would avoid confusion with multiple execution environments (ie. multiple OpenCL command_queues, multiple threads, etc.). Probably in same way allocating memory to reuse across multiple threads could be solved.

> Modify the execution environment to automatically keep track of what's been allocated, so that it can be automatically cleaned up at teardown instead of requiring an explicit deallocation call.

Explicit deallocation calls provide much more flexibility. Do we really want to keep kernels that operate on constant data through whole execution, same for temporary buffers for those kernels? I don't see any upside to this except shorter IR.

> Replace the copy-from-existing-alloc semantics of comp.alloc with explicit comp.schedule_write calls.

I agree this is heavily overused right now, but original idea was to actually avoid copying of user data with `CL_MEM_USE_HOST_PTR`. I'd propose to split into `comp.schedule_write` by default and keep possibility to merge those later after some analysis.

> The generated code also needs a pass to combine waits and downstream operations that are depending on those waits.

Already in progress as #1412.

**Comment by kdobros** [comment]
PS. Rob, let me know if I can somehow help with implementing those changes

**Comment by earhart** [comment]
> Hey Rob, I have a bunch of comments to make, can we just post the RFC to a new issue?

Does that make it easier to make comments?  (I'm not sure how this works / should work...)

> There are a bunch of places where we say "we considered", but I think you meant "I (Rob) considered". Hopefully these are still open for discussion, because I've reached different conclusions on some of them, and would like to add more context to others which will hopefully mean we can reach a consensus.

These are absolutely all open for discussion.  By the end, the goal is to make it a "we".

**Comment by earhart** [comment]
> * I'd like to rename `plaidml_execute` to `plaidml_main`

Why?

> * I propose that instead of using `kidx` and `midx`, that we create new data types that represent kernels and memory chunks and then pass those into the `plaidml_main()` function. There's a bunch of values that don't go anywhere currently, there's a bunch of `comp.alloc` in `init` that I think we should pass those values to `main`. Same goes for kernels, the result of a `create_kernel` should get passed to `main`. Then `schedule` would use that value (and we could drop the `kidx`).
> * I'm not sure we need a `get_alloc` if we just passed the memory chunk to `main`, we could just use the value directly.

What's the ABI as perceived by JitExecutable?  And are you thinking of passing them all as individual values, or as some sort of composite structured type?

I'm having trouble seeing the benefits of your proposal; could you elaborate a bit on what this buys us?

**Comment by earhart** [comment]
> > We considered adding constant folding, but decided to defer it for now (do note how this could be used to optimize the code above a bit).
> 
> I'm actively working on this, so this is inaccurate. A PR will soon be submitted that does constant buffer folding.

Interesting.  Could you write up your design and go through review before submitting any code for this?  There are some pretty obvious overlaps with the current proposal we're talking about (since presumably you'd want this to happen once, when the executable is created); I wonder whether it'd be worth merging the designs.

**Comment by earhart** [comment]
> > Note that we do not need or want to reify a !comp.kernel type for this, since we're going to use the exeecution environment as an opaque container. Instead, these operations should take an execution environment and a kernel index.
> 
> Why? Remember that MLIR uses values for basic things like canonicalizations and CSE. By using values we get these transformations for free.

Because this design packages everything up into the execution environment, there's no need for now to reify a kernel type; YAGNI.  We could actually do the same thing for memory (or at least create a separate type for device memory), but that would involve more changes, and I think we need to discuss the entire way we're modeling memory; it's a bigger change and not one I want to get into right now.

**Comment by flaub** [comment]
If we use values, we get lots of MLIR transformations for free. For instance, let's say we want to `replaceAllUsesWith`, how do we do that with `kidx`?

**Comment by earhart** [comment]
> > De-duplicate identical kernels.
> 
> We get this for free if we use values for kernels and we mark `create_kernel` as `NoSideEffect`. Then we have to ensure that all the attributes specified to the op guarantee its uniqueness.

I like this -- that's a good reason to have a kernel type.  So, we could create a kernel, and stuff it into the execution environment as a separate operation...

**Comment by earhart** [comment]
> If we use values, we get lots of MLIR transformations for free. For instance, let's say we want to `replaceAllUsesWith`, how do we do that with `kidx`?

What's a more concrete example where we'd need such a transform?

**Comment by flaub** [comment]
Pretty much all transformations I can think of. The dialect conversion/legalization framework, data flow analysis, the list really goes on. The question really is, what *can't* we do with values.

**Comment by earhart** [comment]
> Pretty much all transformations I can think of. The dialect conversion/legalization framework, data flow analysis, the list really goes on. The question really is, what _can't_ we do with values.

No, I mean, what's the pass where we'd do this?

And would it be sufficient to define a `comp.get_kernel` taking a kidx, and then use the resulting value for launches?

**Comment by jbruestle** [comment]
So overall, I think it's great to get this in a doc like this.  Not sure if this is the optimal forum for discussion, but better than nothing I guess.  First off, some point we seem to have consensus on (feel free to disagree I misread):

1) Overall design with 3 functions and overall process of moving things to setup/teardown (and naming wise, I don't think it's critical, but I personally like 'exec' rather than main, just since it's less overloaded)
2) Seperation of create_kernel + launch_kernel
3) Adding device to create_kernel (since this matches the underlying API)
4) Make an explicit schedule_write

The biggest point of disagreement seems to be over the index / mlir::Value representation of buffers.  I would generally think that values would be better, however I think Rob's point is: If there are say 20 kernels made in init, how do we pass then to exec?  We can certainly modify exec to have 20 more parameters, but that means we now have a much more variant entry point into 'exec' for LLVM lowering, etc.  Now clearly, we need to have a variant entry point no matter what, since we have a variable number of user buffers, so plausibly it's not too terrible to just have init have 20 output params and exec have 20 additional input params, but I think that perhaps that is @earhart's concern.  Additionally, we probably need some tracking of how many/type of params in executable, etc.

Personally however, I think that if we don't use mlir::Value, we basically will end up having much more complexity to our passes.  For example: Let's imagine I want to write a memory reuse pass.  My first question is: For a given allocation, who uses it?  If it's identified by an integer, how do I find the users?  A linear scan?  Some data structure on side (which ends up being a reimplementation of use-def chains)?  Since I imagine we will want to do a lot of optimizations while things are in comp, I think we should make it as easy as possible.  If we want to fix the issue regarding variable entry points to exec, we can always do a final pass before lowering to LLVM that packs / unpacks intermediates into a context object (plausibly reusing execenv), but doing it too early (i.e. having it be the primary representation) will almost certainly make transforms more difficult.

Also, another possible argument for putting kernels etc into the execenv might be for teardown on failed construction (i.e. failures during init), but there is nothing preventing execenv from keeping a copy of all the memory allocs / kernels (since it's used to construct them), even if we use mlir::Valule.  So overall, I'm for mlir::Value.

Finally, I agree with @kdobros that we should retain explicit destruction, since alloc/dealloc during exec may make sense in some cases, and we don't want to make things impossible to represent just because they are uncommon.

@earhart Can you write up a second draft and try to incorporate all of the changes discussed?

**Comment by flaub** [comment]
A new ask for the execution API is to allow users to specify different buffers for each invocation. Right now, pointers are specified at Executable construction time. This change would allow the removal of a buffer copy for at least the CPU backend. Users could do double-buffering, for example, where one buffer is being used in an invocation while the other one is being populated from a source like a camera.

**Comment by flaub** [comment]
Sorry about that, I accidentally fat-fingered the close button.

**Comment by earhart** [comment]
@jbruestle Frank and I had a good chat about this, and came up with a better design -- I'm working on a revision.  :-)

**Comment by earhart** [comment]
... also, I'm thinking we might want to work on this as a PR in the main repository, instead -- it'll be easier to comment on specific bits.  https://github.com/plaidml/plaidml/pull/1453

**Comment by adstraw** [comment]
Solved by @earhart  and @jbruestle through a number of PRs:

https://github.com/plaidml/plaidml/pull/1583
https://github.com/plaidml/plaidml/pull/1584
https://github.com/plaidml/plaidml/pull/1594
https://github.com/plaidml/plaidml/pull/1607
https://github.com/plaidml/plaidml/pull/1624
https://github.com/plaidml/plaidml/pull/1661

There remains some work to be done to hoist / remove redundant memory transfers.  To be done in a separate issue.
