### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'threshold'

### ISSUE THREAD

**Issue by cgodfreyUW** [plaidml/plaidml#205]
Just trying to follow the "getting started" section of [https://keras.io/getting-started/sequential-model-guide/](url), and when I copy-paste 
`from keras.models import Sequential
from keras.layers import Dense, Activation

model = Sequential([
    Dense(32, input_shape=(784,)),
    Activation('relu'),
    Dense(10),
    Activation('softmax'),
])` I get the following error:

`TypeError: __init__() got an unexpected keyword argument 'threshold'`

Kind of seems like this is related to #170 but the solution there (updating versions) didn't seem applicable, since I'm running 0.3.5 for both.  Any help would be appreciated!

More complete trace-back:

`TypeError                                 Traceback (most recent call last)
<ipython-input-34-341dd7d67172> in <module>
      3     Activation('relu'),
      4     Dense(10),
----> 5     Activation('softmax'),
      6 ])

~/anaconda3/envs/larghissimo/lib/python3.6/site-packages/keras/engine/sequential.py in __init__(self, layers, name)
     91         if layers:
     92             for layer in layers:
---> 93                 self.add(layer)
     94 
     95     @property

~/anaconda3/envs/larghissimo/lib/python3.6/site-packages/keras/engine/sequential.py in add(self, layer)
    179                 self.inputs = network.get_source_inputs(self.outputs[0])
    180         elif self.outputs:
--> 181             output_tensor = layer(self.outputs[0])
    182             if isinstance(output_tensor, list):
    183                 raise TypeError('All layers in a Sequential model '

~/anaconda3/envs/larghissimo/lib/python3.6/site-packages/keras/engine/base_layer.py in __call__(self, inputs, **kwargs)
    455             # Actually call the layer,
    456             # collecting output(s), mask(s), and shape(s).
--> 457             output = self.call(inputs, **kwargs)
    458             output_mask = self.compute_mask(inputs, previous_mask)
    459 

~/anaconda3/envs/larghissimo/lib/python3.6/site-packages/keras/layers/core.py in call(self, inputs)
    297 
    298     def call(self, inputs):
--> 299         return self.activation(inputs)
    300 
    301     def get_config(self):

~/anaconda3/envs/larghissimo/lib/python3.6/site-packages/keras/activations.py in relu(x, alpha, max_value, threshold)
    128         A tensor.
    129     """
--> 130     return K.relu(x, alpha=alpha, max_value=max_value, threshold=threshold)
    131 
    132 

~/anaconda3/envs/larghissimo/lib/python3.6/site-packages/plaidml/tile.py in function(cls, *args, **kwargs)
    253             raise LogicError(
    254                 'Operation.function is defined on subclasses of Operation, not Operation itself.')
--> 255         operation = cls(*args, **kwargs)
    256         if len(operation.output_tuple) == 1:
    257             return operation.output_tuple[0]`

**Comment by brianretford** [comment]
Are you using 2.2.4? The next release or one shortly after will support 2.2.4, 2.2.2 doesn’t, specifically because of keras changing the backend api. I wish they wouldn’t do that for minor version revisions.

On Dec 1, 2018, at 12:38 PM, Charlie Godfrey <notifications@github.com<mailto:notifications@github.com>> wrote:


Just trying to follow the "getting started" section of https://keras.io/getting-started/sequential-model-guide/<url>, and when I copy-paste
`from keras.models import Sequential
from keras.layers import Dense, Activation

model = Sequential([
Dense(32, input_shape=(784,)),
Activation('relu'),
Dense(10),
Activation('softmax'),
])` I get the following error:

TypeError: __init__() got an unexpected keyword argument 'threshold'

Kind of seems like this is related to #170<https://github.com/plaidml/plaidml/issues/170> but the solution there (updating versions) didn't seem applicable, since I'm running 0.3.5 for both. Any help would be appreciated!

More complete trace-back:

`TypeError Traceback (most recent call last)
in
3 Activation('relu'),
4 Dense(10),
----> 5 Activation('softmax'),
6 ])

~/anaconda3/envs/larghissimo/lib/python3.6/site-packages/keras/engine/sequential.py in init(self, layers, name)
91 if layers:
92 for layer in layers:
---> 93 self.add(layer)
94
95 @Property<https://github.com/Property>

~/anaconda3/envs/larghissimo/lib/python3.6/site-packages/keras/engine/sequential.py in add(self, layer)
179 self.inputs = network.get_source_inputs(self.outputs[0])
180 elif self.outputs:
--> 181 output_tensor = layer(self.outputs[0])
182 if isinstance(output_tensor, list):
183 raise TypeError('All layers in a Sequential model '

~/anaconda3/envs/larghissimo/lib/python3.6/site-packages/keras/engine/base_layer.py in call(self, inputs, **kwargs)
455 # Actually call the layer,
456 # collecting output(s), mask(s), and shape(s).
--> 457 output = self.call(inputs, **kwargs)
458 output_mask = self.compute_mask(inputs, previous_mask)
459

~/anaconda3/envs/larghissimo/lib/python3.6/site-packages/keras/layers/core.py in call(self, inputs)
297
298 def call(self, inputs):
--> 299 return self.activation(inputs)
300
301 def get_config(self):

~/anaconda3/envs/larghissimo/lib/python3.6/site-packages/keras/activations.py in relu(x, alpha, max_value, threshold)
128 A tensor.
129 """
--> 130 return K.relu(x, alpha=alpha, max_value=max_value, threshold=threshold)
131
132

~/anaconda3/envs/larghissimo/lib/python3.6/site-packages/plaidml/tile.py in function(cls, *args, **kwargs)
253 raise LogicError(
254 'Operation.function is defined on subclasses of Operation, not Operation itself.')
--> 255 operation = cls(*args, **kwargs)
256 if len(operation.output_tuple) == 1:
257 return operation.output_tuple[0]`

**Comment by cgodfreyUW** [comment]
Hey thanks for your quick response! Downgraded to keras 2.2.2 and everything seems to be functioning. 

Yeah the Keras folks should really be working with you every step of the way! Right now Keras + PlaidML seems like the only viable option for working on a non-NVIDIA GPU. Please continue to combine forces and fight that monopoly, we'll all be grateful.
