### ISSUE TITLE
Problem with Pypi plaidml-keras install

### ISSUE THREAD

**Issue by LanceNorskog** [plaidml/plaidml#209]
I followed the Install page instructions for MacOS and got this. Does anybody know what's going on? Is the Pypi archive damaged in some way?

$ pip install --no-cache-dir -U --timeout 180 plaidml-keras 
Collecting plaidml-keras
  Downloading https://files.pythonhosted.org/packages/97/39/f53511f15c71280449bb01e2f7825e90c1e42d4ff2e5b1afedef82b926d9/plaidml_keras-0.3.5-py2.py3-none-any.whl
Collecting six (from plaidml-keras)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting plaidml (from plaidml-keras)
  Downloading https://files.pythonhosted.org/packages/a8/7e/d9f8280a035434132b3c9463c05dfe0150e4b10ca5c2a94a642683d18c90/plaidml-0.3.5-py2.py3-none-macosx_10_10_x86_64.whl (14.2MB)
    98% |███████████████████████████████▋| 14.0MB 182kB/s eta 0:00:02
Collecting keras==2.2.2 (from plaidml-keras)
  Downloading https://files.pythonhosted.org/packages/34/7d/b1dedde8af99bd82f20ed7e9697aac0597de3049b1f786aa2aac3b9bd4da/Keras-2.2.2-py2.py3-none-any.whl (299kB)
    100% |████████████████████████████████| 307kB 1.9MB/s 
Collecting scipy>=0.14 (from keras==2.2.2->plaidml-keras)
  Downloading https://files.pythonhosted.org/packages/d1/d6/3eac96ffcf7cbeb37ed72982cf3fdd3138472cb04ab32cdce1f444d765f2/scipy-1.1.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (16.8MB)
    74% |███████████████████████▉        | 12.5MB 245kB/s eta 0:00:18
Collecting keras-preprocessing==1.0.2 (from keras==2.2.2->plaidml-keras)
  Downloading https://files.pythonhosted.org/packages/71/26/1e778ebd737032749824d5cba7dbd3b0cf9234b87ab5ec79f5f0403ca7e9/Keras_Preprocessing-1.0.2-py2.py3-none-any.whl
Collecting numpy>=1.9.1 (from keras==2.2.2->plaidml-keras)
  Downloading https://files.pythonhosted.org/packages/c0/b9/2b485bb32d0b26631f433580d90daad5dea830e6dc5bd18c4f227b1829f7/numpy-1.15.4-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (24.5MB)
    7% |██▋                             | 2.0MB 1.1MB/s eta 0:00:21
Collecting keras-applications==1.0.4 (from keras==2.2.2->plaidml-keras)
  Downloading https://files.pythonhosted.org/packages/54/90/8f327deaa37a71caddb59b7b4aaa9d4b3e90c0e76f8c2d1572005278ddc5/Keras_Applications-1.0.4-py2.py3-none-any.whl (43kB)
    100% |████████████████████████████████| 51kB 670kB/s 
Collecting pyyaml (from keras==2.2.2->plaidml-keras)
  Downloading https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz (270kB)
    100% |████████████████████████████████| 276kB 669kB/s 
Collecting h5py (from keras==2.2.2->plaidml-keras)
  Downloading https://files.pythonhosted.org/packages/8c/66/e43692260b2f5361390dbb926e598e84b3491682155e6b7b31fc8516d993/h5py-2.8.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (6.1MB)
    26% |████████▍                       | 1.6MB 1.5MB/s eta 0:00:03
THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    plaidml from https://files.pythonhosted.org/packages/a8/7e/d9f8280a035434132b3c9463c05dfe0150e4b10ca5c2a94a642683d18c90/plaidml-0.3.5-py2.py3-none-macosx_10_10_x86_64.whl#sha256=d79d9c42cf769eb61d5cb7857f39c23bdf8ca135a344510762cbcd529d9fa56d (from plaidml-keras):
        Expected sha256 d79d9c42cf769eb61d5cb7857f39c23bdf8ca135a344510762cbcd529d9fa56d
             Got        b499622f183b3321bbd0fb9f67202665163a4f8d878358c39b9c209295b39f23

    scipy>=0.14 from https://files.pythonhosted.org/packages/d1/d6/3eac96ffcf7cbeb37ed72982cf3fdd3138472cb04ab32cdce1f444d765f2/scipy-1.1.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl#sha256=340ef70f5b0f4e2b4b43c8c8061165911bc6b2ad16f8de85d9774545e2c47463 (from keras==2.2.2->plaidml-keras):
        Expected sha256 340ef70f5b0f4e2b4b43c8c8061165911bc6b2ad16f8de85d9774545e2c47463
             Got        3764c36498233b66ed5040e1979971d70bb850f789133386ffda88ce2c258474

    numpy>=1.9.1 from https://files.pythonhosted.org/packages/c0/b9/2b485bb32d0b26631f433580d90daad5dea830e6dc5bd18c4f227b1829f7/numpy-1.15.4-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl#sha256=18e84323cdb8de3325e741a7a8dd4a82db74fde363dce32b625324c7b32aa6d7 (from keras==2.2.2->plaidml-keras):
        Expected sha256 18e84323cdb8de3325e741a7a8dd4a82db74fde363dce32b625324c7b32aa6d7
             Got        0f4a634834b62968ae6127e3eff69279a842e649fea9e01b10b2d80dcd44409b

    h5py from https://files.pythonhosted.org/packages/8c/66/e43692260b2f5361390dbb926e598e84b3491682155e6b7b31fc8516d993/h5py-2.8.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl#sha256=56d259d56822b70881760b243957f04a0cf133f0ec65eae6a33f562826aee899 (from keras==2.2.2->plaidml-keras):
        Expected sha256 56d259d56822b70881760b243957f04a0cf133f0ec65eae6a33f562826aee899
             Got        ca0e6e074e4d75835eb4c708c616e9e818f89a3aecf9d3e9cfbeb89738f2fc7b

**Comment by brianretford** [comment]
I’ve never seen that and just installed it a few hours ago. Note that the hashes are wrong for everything (i.e. scipy) — if you just install scipy what happens?

On Dec 7, 2018, at 7:45 PM, Lance Norskog <notifications@github.com<mailto:notifications@github.com>> wrote:


I followed the Install page instructions for MacOS and got this. Does anybody know what's going on? Is the Pypi archive damaged in some way?

$ pip install --no-cache-dir -U --timeout 180 plaidml-keras
Collecting plaidml-keras
Downloading https://files.pythonhosted.org/packages/97/39/f53511f15c71280449bb01e2f7825e90c1e42d4ff2e5b1afedef82b926d9/plaidml_keras-0.3.5-py2.py3-none-any.whl
Collecting six (from plaidml-keras)
Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting plaidml (from plaidml-keras)
Downloading https://files.pythonhosted.org/packages/a8/7e/d9f8280a035434132b3c9463c05dfe0150e4b10ca5c2a94a642683d18c90/plaidml-0.3.5-py2.py3-none-macosx_10_10_x86_64.whl (14.2MB)
98% |███████████████████████████████▋| 14.0MB 182kB/s eta 0:00:02
Collecting keras==2.2.2 (from plaidml-keras)
Downloading https://files.pythonhosted.org/packages/34/7d/b1dedde8af99bd82f20ed7e9697aac0597de3049b1f786aa2aac3b9bd4da/Keras-2.2.2-py2.py3-none-any.whl (299kB)
100% |████████████████████████████████| 307kB 1.9MB/s
Collecting scipy>=0.14 (from keras==2.2.2->plaidml-keras)
Downloading https://files.pythonhosted.org/packages/d1/d6/3eac96ffcf7cbeb37ed72982cf3fdd3138472cb04ab32cdce1f444d765f2/scipy-1.1.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (16.8MB)
74% |███████████████████████▉ | 12.5MB 245kB/s eta 0:00:18
Collecting keras-preprocessing==1.0.2 (from keras==2.2.2->plaidml-keras)
Downloading https://files.pythonhosted.org/packages/71/26/1e778ebd737032749824d5cba7dbd3b0cf9234b87ab5ec79f5f0403ca7e9/Keras_Preprocessing-1.0.2-py2.py3-none-any.whl
Collecting numpy>=1.9.1 (from keras==2.2.2->plaidml-keras)
Downloading https://files.pythonhosted.org/packages/c0/b9/2b485bb32d0b26631f433580d90daad5dea830e6dc5bd18c4f227b1829f7/numpy-1.15.4-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (24.5MB)
7% |██▋ | 2.0MB 1.1MB/s eta 0:00:21
Collecting keras-applications==1.0.4 (from keras==2.2.2->plaidml-keras)
Downloading https://files.pythonhosted.org/packages/54/90/8f327deaa37a71caddb59b7b4aaa9d4b3e90c0e76f8c2d1572005278ddc5/Keras_Applications-1.0.4-py2.py3-none-any.whl (43kB)
100% |████████████████████████████████| 51kB 670kB/s
Collecting pyyaml (from keras==2.2.2->plaidml-keras)
Downloading https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz (270kB)
100% |████████████████████████████████| 276kB 669kB/s
Collecting h5py (from keras==2.2.2->plaidml-keras)
Downloading https://files.pythonhosted.org/packages/8c/66/e43692260b2f5361390dbb926e598e84b3491682155e6b7b31fc8516d993/h5py-2.8.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (6.1MB)
26% |████████▍ | 1.6MB 1.5MB/s eta 0:00:03
THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
plaidml from https://files.pythonhosted.org/packages/a8/7e/d9f8280a035434132b3c9463c05dfe0150e4b10ca5c2a94a642683d18c90/plaidml-0.3.5-py2.py3-none-macosx_10_10_x86_64.whl#sha256=d79d9c42cf769eb61d5cb7857f39c23bdf8ca135a344510762cbcd529d9fa56d (from plaidml-keras):
Expected sha256 d79d9c42cf769eb61d5cb7857f39c23bdf8ca135a344510762cbcd529d9fa56d
Got b499622f183b3321bbd0fb9f67202665163a4f8d878358c39b9c209295b39f23

scipy>=0.14 from https://files.pythonhosted.org/packages/d1/d6/3eac96ffcf7cbeb37ed72982cf3fdd3138472cb04ab32cdce1f444d765f2/scipy-1.1.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl#sha256=340ef70f5b0f4e2b4b43c8c8061165911bc6b2ad16f8de85d9774545e2c47463 (from keras==2.2.2->plaidml-keras):
    Expected sha256 340ef70f5b0f4e2b4b43c8c8061165911bc6b2ad16f8de85d9774545e2c47463
         Got        3764c36498233b66ed5040e1979971d70bb850f789133386ffda88ce2c258474

numpy>=1.9.1 from https://files.pythonhosted.org/packages/c0/b9/2b485bb32d0b26631f433580d90daad5dea830e6dc5bd18c4f227b1829f7/numpy-1.15.4-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl#sha256=18e84323cdb8de3325e741a7a8dd4a82db74fde363dce32b625324c7b32aa6d7 (from keras==2.2.2->plaidml-keras):
    Expected sha256 18e84323cdb8de3325e741a7a8dd4a82db74fde363dce32b625324c7b32aa6d7
         Got        0f4a634834b62968ae6127e3eff69279a842e649fea9e01b10b2d80dcd44409b

h5py from https://files.pythonhosted.org/packages/8c/66/e43692260b2f5361390dbb926e598e84b3491682155e6b7b31fc8516d993/h5py-2.8.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl#sha256=56d259d56822b70881760b243957f04a0cf133f0ec65eae6a33f562826aee899 (from keras==2.2.2->plaidml-keras):
    Expected sha256 56d259d56822b70881760b243957f04a0cf133f0ec65eae6a33f562826aee899
         Got        ca0e6e074e4d75835eb4c708c616e9e818f89a3aecf9d3e9cfbeb89738f2fc7b

**Comment by LanceNorskog** [comment]
I think it's my problem. I'm on a corporate Mac that has special MITM cert processing.
