### ISSUE TITLE
Plaidml deepmg package compatibility 

### ISSUE THREAD

**Issue by dsaito** [plaidml/plaidml#216]
This is more of a question, rather than an issue. I have a 6xRX580 multi GPU rig. I am planning to use the deepmg package for transformation of metagenomic data into images, but ran into the following disclaimer: 

Prerequisites:
These packaged should be installed before using Met2Img (updated to 21/02/2018):
tensorflow	1.5.0
sklearn	0.19.1
keras	2.1.3
numpy	1.14.0
matplotlib	2.1.2

My question is: can I simply replace tensorflow by plaidml for this to work with my setup? Any help is appreciated.

**Comment by SleepProgger** [comment]
I don't know deepmg, but from my experience with other projects "requiring keras + tensorflow":
It depends. You may get away with no tensorflow at all, but most likely you'd need the cpu version of tensorflow.
If the project doesn't use tf layers everything should just work by setting plaidml as backend.
Otherwise you might have to patch the project and replace tf specific parts with raw keras or plaidml functions.
Keras doesn't seem to like if you start mixing backends (understandably).
*Not sure this is the correct place for this tho*

**Comment by brianretford** [comment]
Let us know if this works or if there are specific errors we can help to address.
