### ISSUE TITLE
`No module named plaidml.plaidml_setup`

### ISSUE THREAD

**Issue by yokoe** [plaidml/plaidml#23]
I am trying to build and install plaidml on macOS 10.12.

When I try to run `plaidml-setup`, I get `No module named plaidml.plaidml_setup`.

What I did was

```
virtualenv --system-site-packages ~/plaidml
source ~/plaidml/bin/activate
git clone https://github.com/plaidml/plaidml.git
bazel build -c opt plaidml:wheel plaidml/keras:wheel
pip install -U bazel-bin/plaidml/*whl bazel-bin/plaidml/keras/*whl
```

I am using bazel-0.7.0.

Any advice would be appreciated.

**Comment by jbruestle** [comment]
In a few weeks we should be releasing official Mac support, at which point you should just be able to do a pip install, but in the meantime:

I ran into this same issue during some early testing.  It is due to a very out of date version of setup tools (among other packages).  The result is that the packaging process doesn't actually add the proper files.  Upgrading setup tools on OSX is a bit special, see:

https://stackoverflow.com/questions/33234665/upgrading-setuptools-on-osx-el-capitan

I believe you also need to update 'wheel' and possibly one or two other packages.  Unfortunately, we are still in the process of moving our internal Mac build automation into something we can open source, so I don't have a definitive list right now.

Hopefully that will help, and with luck we should have official support soon!  If you'd like to be added to the beta testers list please email info@vertex.ai.

**Comment by yokoe** [comment]
Thank you, I could build it successfully now!
And official Mac support would be great!
