### ISSUE TITLE
Where are the kernels?

### ISSUE THREAD

**Issue by newling** [plaidml/plaidml#28]
Hi, I can't find any OpenCL kernels in the source dir, and was wondering where they could be (greps for "gemm" and "__kernel" come up empty). Perhaps I don't understand where plaidml fits in, I would have thought the bulk of the work would be writing OpenCL performant kernels though. Thanks for the clarification.

**Comment by jbruestle** [comment]
Excellent question!  You are correct that there are not OpenCL kernels in the source.  This is because they are generated at runtime automatically.

As you point out, efficient OpenCL kernels are the core of high performance machine learning systems.  Unfortunately, it's rather complex to write a good kernel, and kernels which are efficient on one platform may not be efficient on another.  One has to take into account things like various cache sizes, the nature of the vectors units, support for local memory, banking limitations of local memory, coalescing of global memory access, etc, and these properties differ wildly from platform to platform.  See https://www.nvidia.com/content/cudazone/CUDABrowser/downloads/papers/NVIDIA_OpenCL_BestPracticesGuide.pdf for some examples.  

When looking at the large number of modern GPUs, especially in the embedded space, as well as the increasing number of ML operations a modern framework supports, it becomes clear that writing a custom high performance kernel for every operation for every platform is a herculean engineering effort.

So we asked ourselves, "Why can't a computer find the optimal kernel for a given situation?"  This is a very hard optimization problem, but the key was realizing that we don't need to solve it for arbitrary code, but for the set of operations needed by an ML stack.  This lead us to develop a domain specific language, Tile, which can expresses all the required operations (convolution, max-pool, etc), while still being highly amenable to analysis and optimization.

You can see the Python code that generates the Tile code for various Keras operations in plaidml/keras/backend.py.  It's less than 3k lines of code.  This is translated and optimized into a semantic tree representation of code via tile/lang/*, and emitted as OpenCL by tile/hal/opencl/*.  We will be writing some blog posts in the near future covering the process in more detail.  If your curious to look at the generated kernels, you can add the following line after importing plaidml to enable very verbose logging:

`plaidml._internal_set_vlog(3)`

Hope that helps!

**Comment by newling** [comment]
Great answer, thanks! Looking forward to your blog posts.

**Comment by scott-gray** [comment]
I think easier than enabling the vlog is this (after running a benchmark):

`cd ~/.nv/ComputeCache`
`cat */*/* | less`
search for __kernel

It might be nice if the kernel names contained some info on what ops they implement.
