### ISSUE TITLE
Tensorflow 2.0

### ISSUE THREAD

**Issue by leedrake5** [plaidml/plaidml#281]
Given that [Tensorflow 2.0 is adopting Keras-style interfaces](https://hackernoon.com/tensorflow-is-dead-long-live-tensorflow-49d3e975cf04), will this provide an opportunity to use plaidml with Tensorflow 2.0?

**Comment by iperov** [comment]
how tensorflow related to plaidml ?
plaidml implements keras interface.
tf 2.0 just enables eager execution of tensors, like pytorch .

**Comment by brianretford** [comment]
@iperov - really grateful for your contributions but would really appreciate more civility in your interactions with other community members

We’re going to publishing our roadmap soon and soliciting community feedback.

I actually do expect us to support tensorflow 2.0. You can read more about MLIR at c4ml.org, we expect to hook in through this as it provides a reasonable abstraction layer to interoperate with tensorflow.

We actually had a tf backend before we open-sourced things but it was a total hack because the original tensorflow never contained a proper backend abstraction

**Comment by brianretford** [comment]
(Google is being very quiet about the details of MLIR, I actually expect it to contain similar elements as plaidml / stripe once they fully roll it out. They have stated it will be the way to integrate w tensorflow. Personally I’m pretty excited about what I know about MLIR)

**Comment by iperov** [comment]
>  appreciate more civility in your interactions with other community members

I said what I know about plaidml.

**Comment by leedrake5** [comment]
> @iperov - really grateful for your contributions but would really appreciate more civility in your interactions with other community members
> 
> We’re going to publishing our roadmap soon and solicit community feedback.
> 
> I actually do expect us to support tensorflow 2.0. You can read more about MLIR at c4ml.org, we expect to hook in through this as it provides a reasonable abstraction layer to interoperate with tensorflow.
> 
> We actually had a tf backend before we open-sourced things but it was a total hack because the original tensorflow never contained a proper backend abstraction

Thank you for your dedicated work on plaidml - it has opened a lot of doors to machine learning that would have otherwise been closed. Exciting to hear about possible support for TensorFlow 2.0!

**Comment by brianretford** [comment]
Of course! We’re really excited about the stuff we’ll have coming out next week and in the following releases

On Mar 30, 2019, at 10:58 AM, Lee Drake <notifications@github.com<mailto:notifications@github.com>> wrote:


@iperov<https://github.com/iperov> - really grateful for your contributions but would really appreciate more civility in your interactions with other community members

We’re going to publishing our roadmap soon and solicit community feedback.

I actually do expect us to support tensorflow 2.0. You can read more about MLIR at c4ml.org<http://c4ml.org>, we expect to hook in through this as it provides a reasonable abstraction layer to interoperate with tensorflow.

We actually had a tf backend before we open-sourced things but it was a total hack because the original tensorflow never contained a proper backend abstraction

Thank you for your dedicated work on plaidml - it has opened a lot of doors to machine learning that would have otherwise been closed. Exciting to hear about possible support for TensorFlow 2.0!

**Comment by iperov** [comment]
> Exciting to hear about possible support for TensorFlow 2.0!

do you mean `plaidml.tf` could be exactly the same as `tf` in the future ? or what

**Comment by hoangtubatu123** [comment]
does plaidml support tensorflow ???

**Comment by iperov** [comment]
@hoangtubatu123 it supports keras

**Comment by hoangtubatu123** [comment]
okay. i'm waitting for supporting tensorflow =)

**Comment by earhart** [comment]
FWIW, PlaidML works with Tensorflow if you use nGraph's TensorFlow support and the PlaidML backend -- you might need to compile things yourself, though (I'm not sure what the status is of getting an nGraph-TF release with PlaidML support built into the wheel).

**Comment by iperov** [comment]
@hoangtubatu123 
> okay. i'm waitting for supporting tensorflow =)

why? keras much better and portable

**Comment by brianretford** [comment]
Our tensorflow support will be provided through ngraph.
