### ISSUE TITLE
Bazel build fails due to wrong llvm URL

### ISSUE THREAD

**Issue by daniloefl** [plaidml/plaidml#329]
Dear PlaidML developers,

unfortunately, it seems that the Bazel configuration for PlaidML has the wrong URL needed to download LLVM. The following change was needed to make a successful compilation in the master branch as of today ( version given by git rev-parse HEAD : f3991105ad895add5af750b9c318a74d0a9acd14 ).

Note that the only issue is a typo in "8.0.8", which should have been "8.0.0". Even the SHA256 matches correctly the one for the version 8.0.0 after the correction.

Best regards,
Danilo

```
diff --git a/bzl/workspace.bzl b/bzl/workspace.bzl
index f95ff05..9aa48cb 100644
--- a/bzl/workspace.bzl
+++ b/bzl/workspace.bzl
@@ -157,7 +157,7 @@ def configure_protobuf():
 def configure_llvm():
     http_archive(
         name = "llvm",
-        url = "http://releases.llvm.org/8.0.8/llvm-8.0.0.src.tar.xz",
+        url = "http://releases.llvm.org/8.0.0/llvm-8.0.0.src.tar.xz",
         sha256 = "8872be1b12c61450cacc82b3d153eab02be2546ef34fa3580ed14137bb26224c",
         strip_prefix = "llvm-8.0.0.src",
         build_file = str(Label("//vendor/llvm:llvm.BUILD")),
```

**Comment by dgkutnic** [comment]
Hi Danilo,

We've made this fix and it'll be in our next release. Thanks for using PlaidML!

**Comment by brianretford** [comment]
Yes this has actually been fixed in a PR that we’ll get integrated soon. Sorry for the current bug

Sent from my iPhone

On Jun 4, 2019, at 1:13 AM, Danilo Enoque Ferreira de Lima <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear PlaidML developers,

unfortunately, it seems that the Bazel configuration for PlaidML has the wrong URL needed to download LLVM. The following change was needed to make a successful compilation in the master branch as of today ( version given by git rev-parse HEAD : f399110<https://github.com/plaidml/plaidml/commit/f3991105ad895add5af750b9c318a74d0a9acd14> ).

Note that the only issue is a typo in "8.0.8", which should have been "8.0.0". Even the SHA256 matches correctly the one for the version 8.0.0 after the correction.

Best regards,
Danilo

diff --git a/bzl/workspace.bzl b/bzl/workspace.bzl
index f95ff05..9aa48cb 100644
--- a/bzl/workspace.bzl
+++ b/bzl/workspace.bzl
@@ -157,7 +157,7 @@ def configure_protobuf():
 def configure_llvm():
     http_archive(
         name = "llvm",
-        url = "http://releases.llvm.org/8.0.8/llvm-8.0.0.src.tar.xz",
+        url = "http://releases.llvm.org/8.0.0/llvm-8.0.0.src.tar.xz",
         sha256 = "8872be1b12c61450cacc82b3d153eab02be2546ef34fa3580ed14137bb26224c",
         strip_prefix = "llvm-8.0.0.src",
         build_file = str(Label("//vendor/llvm:llvm.BUILD")),

**Comment by daniloefl** [comment]
Dear @dgkutnic and @brianretford ,

thanks for the information. The bug was not a big issue and easily traceable: I just thought I would let you know. I will let you close the issue when you prefer (ie: in case you want to wait for the fix to be merged).

Cheers,
Danilo

**Comment by aviallon** [comment]
Was just going to report the bug :P

**Comment by brianretford** [comment]
Fix pushed to master
