### ISSUE TITLE
I use plaidml to parser tile codes to generate kernels, below is one of the kernels it output.what's it ? 

### ISSUE THREAD

**Issue by preFiredman** [plaidml/plaidml#352]
I use plaidml to parser tile codes to generate kernels, below is one of the kernels it output.
I can not correspond it with my tile codes, 
what's it and how should I find out the relationship within the kernels ?
```
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
__kernel void kernel_co_fp32(__global float* out)
{
  out[get_global_id(0)] = (float)0;
}
```

**Comment by earhart** [comment]
This it typical when a kernel doesn't write to every location in an output tensor -- PlaidML pre-zeros the output tensor so that the unwritten elements have well-defined values.

Implementation-wise, the OpenCL backend won't actually generate a kernel for this; it'll be a call to `clEnqueueFillBuffer` or `clEnqueueSVMMemFill`. Likewise, Metal will encode a `fillBuffer` call.
