### ISSUE TITLE
Poor Performance with PlaidML Backend on Mac?

### ISSUE THREAD

**Issue by kmader** [plaidml/plaidml#50]
While I realize it is experimental, the backend seems to work (in 2.7 and 3.5), and different parts of my computer seem to get warm when compared to TF (and CPU usage stays under 100%), but it's half the speed for a basic CNN on MNIST (https://gist.github.com/kmader/ebd1c2a07815e1f227c6e77ec996e928). Is there something I am doing wrong here?

# Model
```
Layer (type)                 Output Shape              Param #   
=================================================================
reshape_1 (Reshape)          (None, 28, 28, 1)         0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 28, 28, 16)        160       
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 26, 26, 16)        2320      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 13, 13, 16)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 13, 13, 16)        2320      
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 11, 11, 16)        2320      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 5, 5, 16)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 400)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                4010      
=================================================================
Total params: 11,130
Trainable params: 11,130
Non-trainable params: 0
```
# Results
## Tensorflow 1.3 CPU
```
CPU times: user 1min 41s, sys: 17.1 s, total: 1min 58s
Wall time: 32.5 s
```
## plaidml backend
```
INFO:plaidml:b'Opening device "intel(r)_iris(tm)_graphics_550.0'
```

- Slowest
```
CPU times: user 44.2 s, sys: 5.76 s, total: 49.9 s
Wall time: 1min 9s
```
- Fastest
```
CPU times: user 43.8 s, sys: 6.03 s, total: 49.8 s
Wall time: 49 s
```

**Comment by brianretford** [comment]
There are a few potential issues here:

1) PlaidML's training performance is poor, as noted in the README. We're working on addressing this.

2) Iris support is still quite experimental and we're working on finding the best parameters for them. The best parameters seem to vary from model to model more on Iris than on NVIDIA or AMD. We're planning on building a parameter scanner to find the optimal parameters for a given device, but we don't have a timeline on that.

3) MNIST is a fairly memory light network, but PlaidML currently doesn't have the best memory usage optimizer (also working on that). We've noticed severe performance degradation on some devices when they are under memory pressure. I'd be surprised if this is affecting an Iris, but who know. You might try decreasing your batch size.

4) PlaidML's compiler is currently kind of slow and doesn't cache things between program runs. We're planning on addressing this as well. This is a small network so it should be less of a problem, but training greatly increases the number of kernels. If you look at plaidbench we deliberately one run batch through before computing timings in order to separate compilation time from runtime. You might try running a lot more epochs and comparing, as the compilation time should amortize to ~0 over a long enough training run.

Let us know your results if you try any of these things.

**Comment by brianretford** [comment]
It's also worth running plaidvision or plaidbench and seeing what kind of results you get.

**Comment by kmader** [comment]
plaidbench gives better results, but I wanted to test it on models I was using. I adapted the test to pre-run on one sample but still had the periodic Analzing Ops, which certainly detracted from performance. 
```
INFO:plaidml:b'Analyzing Ops: 76 of 237 operations complete'
```

**Comment by kmader** [comment]
For retraining VGG16 using MNIST
```
def fancy_model():
    model = Sequential()
    model.add(Reshape((28, 28, 1), input_shape=(784,)))
    model.add(UpSampling2D((2,2)))
    model.add(VGG16(input_shape = (56,56,1), weights = None, classes = 10))
    return model
```
The performance is better but still on the same order of magnitude as CPU.

## Tensorflow 1.3 CPU
```
Epoch 1/1
500/500 [==============================] - 120s - loss: 11.3886 - acc: 0.1040    
500/500 [==============================] - 23s    
Test score: 14.345104805
Test accuracy: 0.11000000003
CPU times: user 6min 46s, sys: 17.1 s, total: 7min 3s
Wall time: 2min 24s
```
## plaidml backend
```
500/500 [==============================] - 77s - loss: 281.3642 - acc: 0.1080     
500/500 [==============================] - 26s    
Test score: 2.30175299263
Test accuracy: 0.13400000006
CPU times: user 40.9 s, sys: 14.1 s, total: 55 s
Wall time: 1min 43s
```

**Comment by brianretford** [comment]
We've done a reasonable amount of perf work, though we still haven't focused on training. What batch size were you using? Definitely on lots of Intel setups you don't notice a perf boost with a batch size of at least 8. Anyway, curious what your numbers are on our latest RC:  `pip install plaidml-keras==0.3.0rc1 plaidml==0.3.0rc1`

**Comment by tzerrell** [comment]
Closing this as stale; if you still have perf concerns please open a new issue

**Comment by martin-etchart** [comment]
Tested training MNIST with batch size 128 and at most the speedup is 2x compared to TF on CPU. with CIFAR and batch size 32 TF on CPU was 1.5x faster than with Plaid. 

I am testing on a Macbook Pro 15' with selected device metal_amd_radeon_pro_560. This was the fastest of all.

All vanilla installed using virtualenv + pip + python3

plaidml==0.6.4
plaidml-keras==0.6.4
tensorflow==1.14.0
Keras==2.2.4
