### ISSUE TITLE
AttributeError: 'Value' object has no attribute 'start'

### ISSUE THREAD

**Issue by iperov** [plaidml/plaidml#545]
code to reproduce:
```
import os
os.environ["KERAS_BACKEND"] = "plaidml.keras.backend"
os.environ["PLAIDML_DEVICE_IDS"] = "opencl_nvidia_geforce_gtx_1060_6gb.0"
import keras
KL = keras.layers

x = KL.Input ( (128,128,64) )
label = KL.Input( (1,), dtype="int32")
y = x[:,:,:, label[0,0] ]
```

error:
```
    y = x[:,:,:, label[0,0] ]
  File "F:\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\plaidm
l\tile.py", line 700, in __getitem__
    return _SliceOf.function(self, key)
  File "F:\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\plaidm
l\tile.py", line 255, in function
    operation = cls(*args, **kwargs)
  File "F:\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\plaidm
l\tile.py", line 411, in __init__
    value.shape.dims, key, idx)
  File "F:\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\plaidm
l\tile.py", line 485, in _parse_slice
    check(key[idx].start)
AttributeError: 'Value' object has no attribute 'start'
```

code works fine on tensorflow.

This code is required to implement NVLabs/FUNIT model.

**Comment by dgkutnic** [comment]
Hi @iperov,

You're seeing this issue because you are slicing `x` with `label`, which is a dynamic slice, and Tile does not currently support dynamic shape slicing. However, we are replacing Tile with a new way of representing operations (Stripe) in the near future, and we are planning to add dynamic shape slicing to Stripe. It will take us some time to fix this issue, but it is high on our priority list and we're actively working on it.

Thanks for providing us with this example. We'll use it to validate dynamic shape slicing in Stripe once it's added.
