### ISSUE TITLE
Support for PyTorch and dynamic computation graphs 

### ISSUE THREAD

**Issue by zaoyang** [plaidml/plaidml#63]
Hi, 

I'd like to get support for Pytorch and support for dynamic computational graph based DL languages. I think this is fairly important as a number of the newest techniques in DL are easily implemented on Pytorch rather than Keras or TF. 

Zao

**Comment by pchankh** [comment]
I second this, please help support Pytorch too..

**Comment by imsrgadich** [comment]
please create support for PyTorch. Thanks in advance!

**Comment by petitgen** [comment]
please, Thanks

**Comment by csjtx1021** [comment]
please, Thanks

**Comment by BigtoC** [comment]
Same here! Please support for PyTorch!

**Comment by brianretford** [comment]
We would love to. All our focus right now is on getting the stripe passes ported over to MLIR and releasing 1.0. There is very proof-of-concept code for supporting PyTorch JIT in the current branch that people could work on, in general it would be nice to see a reasonable bridge into MLIR from the broader community.

**Comment by developersfox** [comment]
PlaidMl is definitely needed for pytorch.. What is the current situation with the porting? Will it work on any pytorch code rather than just jit'ed? And do you have an estimation on when the first version will be available?

**Comment by guy4261** [comment]
Trying to use pytorch to convert to onnx, I then try to convert onnx to plaidml using https://pypi.org/project/onnx-plaidml/ but it fails because `NotImplementedError: ""/version=9" is not implemented by the PlaidML ONNX backend`.

Also, the https://github.com/plaidml/onnx-plaidml repo seems archived.

So how is onnx supported in plaidml (if at all)? Also, does onnx support implicates pytorch-converted-to-onnx support? (For simple cases of course, I'm aware it is possible that not 100% of pytorch is covered right now).

Thanks in advance!

**Comment by shivSD** [comment]
https://github.com/plaidml/plaidml/issues/63#issuecomment-590591518
@brianretford 

Is there any example to code that show how to use pytorch in plaidml.

**Comment by realsarm** [comment]
Any update to this?

**Comment by alimoezzi** [comment]
Is there any example on how to use Pytorch with Plaidml as this issue is closed as completed ? @alheinecke

**Comment by alheinecke** [comment]
sorry, it should be closed as not planned.

**Comment by MultiTrickFox** [comment]
Goodbye fellas. We really hoped and waited for it
